name: Build macOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        arch: [arm64, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build App (macOS ${{ matrix.arch }})
        run: npm run build:packager -- --arch=${{ matrix.arch }}

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GridCast-macOS-${{ matrix.arch }}
          path: dist/GridCast-${{ matrix.arch }}.dmg
